/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package client.view.forms;
import client.view.table.TableModelOrderItems;
import java.util.ArrayList;

import zcommon.domain.Invoice;
import zcommon.domain.Order;
import zcommon.domain.OrderItems;

/**
 *
 * @author Korisnik
 */
public class FormDetailsOfOrderORInvoiceFORUser extends javax.swing.JDialog {

    /**
     * Creates new form FormDetailsOfOrderForUser
     */
    Order o;
    Invoice i;
    
    public FormDetailsOfOrderORInvoiceFORUser(java.awt.Dialog parent, boolean modal, Order o, Invoice i) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.o = o;
        this.i = i;
        
        tblOrders.setModel(new TableModelOrderItems());
        showDetails(o, i);
        
        setSize(600, 600);
        setName("Invoice");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblText = new javax.swing.JLabel();
        lblTextPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("dialogg");

        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOrders);

        lblText.setText("jLabel1");

        lblTextPrice.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextPrice)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TableModelOrderItems.emptyList();
        //System.out.println("list is : " + TableModelOrderItems.getListOfItems().size());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showDetails(Order o, Invoice i) {
        if (i == null) {
            //prikaz od o
            /*System.out.println("o id: " + o.getOrderID());
            JLabel label = new JLabel("Order ID: ");
            //label.setText("Order ID: ");
            //label.setVisible(true);
            //label.setLocation(100, 100);
            JTextField textID = new JTextField(o.getOrderID());
            textID.setVisible(true);
            //textID.setLocation(150, 150);
           newPanel.add(label);
           newPanel.add(textID);*/
            lblText.setText("Order items of order number " + o.getOrderID());
            ArrayList<OrderItems> listOfItems = o.getListOfItem();
            TableModelOrderItems tmoi = (TableModelOrderItems) tblOrders.getModel();
            tmoi.addOrderItems(listOfItems);
            lblTextPrice.setText("Total price is " + o.getTotalAmountPricee());
        } else {
            //prikaz od i
        }
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTextPrice;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
