/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view.forms;

import client.communication.Communication;
import client.controller.ControllerClient;
import client.main.Main;
import client.view.table.TableModelOrderItems;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import zcommon.domain.OrderItems;
import zcommon.domain.User;

/**
 *
 * @author Korisnik
 */
public class UserMainForm extends javax.swing.JFrame {

    /**
     * Creates new form UserMainForm
     */
    
    User u;
    FormAllProductsView allProductsForm;
    FormYourCartUser cartForUserForm;
    FormProfileUser profileForm;
    
    public UserMainForm(User u) {
        super("Welcome user, " + u.getName());
        initComponents();
        this.u = u;
        setLocationRelativeTo(null);
        ControllerClient.getInstance().setUsermf(this);
        setTitle("Main page");
        setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Products");
        jMenu1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jMenuItem1.setText(" Preview");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(" Your cart");
        jMenu2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jMenuItem3.setText("Preview");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Your profile");
        jMenu3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jMenuItem2.setText("Information");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jMenuItem4.setText("Recent shopping");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // all products
        allProductsForm = new FormAllProductsView(this, true, null, u);
        allProductsForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // your cart -> make an order from order items
        cartForUserForm = new FormYourCartUser(this, true, u);
        cartForUserForm.setVisible(true);
        ControllerClient.getInstance().setYourCartf(cartForUserForm);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // profile information + all orders from that user + can leave a comment for a product
        profileForm = new FormProfileUser(this, true, u);
        profileForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FormAllOrdersUser(this, true, u).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            ArrayList<OrderItems> listOfItems = TableModelOrderItems.getListOfItems();
            int nmbOfItems = listOfItems.size();
            if (!listOfItems.isEmpty()) {
                int result = JOptionPane.showConfirmDialog(this, "You have " + nmbOfItems + " items in your cart. Do you really want to logout, you will lose your work?", "Logout", JOptionPane.YES_NO_OPTION);
                if (JOptionPane.YES_OPTION == result) {
                   ControllerClient.getInstance().logout();
                } else if (JOptionPane.NO_OPTION == result){
                    System.out.println("NO");
                    return;
                }
            } else ControllerClient.getInstance().logout();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables

    public void handleProfileUpdated(User updatedUser, boolean signal3) {
        if (signal3) {
            this.u = updatedUser;
            profileForm.setU(updatedUser);
            profileForm.getTxtProfile().setText("Your profile, " + updatedUser.getName());
            JOptionPane.showMessageDialog(profileForm, "Successful");
        } else {
            JOptionPane.showMessageDialog(profileForm, "Something went wrong with updating...");
        }
        
    }

    public void handleSaveOrder(boolean signal4) {
        if (signal4) {
            JOptionPane.showMessageDialog(cartForUserForm, "Success order!!!");
        } else JOptionPane.showMessageDialog(cartForUserForm, "Something went wrong, your order cannot be saved... ");
    }

    public void handleServerStopped(String message) {
        JOptionPane.showMessageDialog(this, message);
        this.dispose();
    }

    public void handleLogout(String messageLogout) {
        JOptionPane.showMessageDialog(this, messageLogout);
        //pokretanje opet sa formom za login
        //this.dispose();
        System.exit(0);
    }

}
